global:
  scrape_interval: 5s      # Scrape metrics every 5 seconds
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'converter-service'
    static_configs:
      - targets: ['host.docker.internal:3000']  # Access host machine from Docker
    metrics_path: '/metrics'
    scrape_interval: 5s

